name: BuildGithub1s

on: 
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0/2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.x

    - name: Clone Github1s Repo
      run: |
        git clone https://github.com/conwnet/github1s.git

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
            {{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        cd github1s
        yarn

    - name: Build
      run: |
        cd github1s
        yarn build
        cd dist
        git init
        ls -a

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GH_TOKEN }}
        publish_dir: ./github1s/dist
        publish_branch: ${{ secrets.TARGET_BRANCH }}
        external_repository: ${{ secrets.TARGET_REPO }}  
                
                
                
                
                
                
